name: Update Fork
on:
  push:
    branches:
    - '*'

jobs:
  update-fork:
    runs-on: ubuntu-latest
    steps:
      - name: GitHub Sync to Upstream Repository
        uses: rovast/sync-upstream-repo@v0.0.1
        with: 
          upstream_repo: https://github.com/UnfiledOppositeQuackIssue/repo-automation-test
          upstream_branch: release4.2 # change this
          downstream_branch: release4.2 # change this
          token: ${{ secrets.AUTOMATION_TOKEN }}
